### ISSUE TITLE
glusterfs support

### ISSUE THREAD

**Issue by erikh** [contiv-experimental/volplugin#335]
glusterfs is another clustered filesystem we can use. I think it'll pair well with how volplugin works.

**Comment by erikh** [comment]
glusterfs configuration distilled:

* use vagrantfile, disable ansible, use box `box-cutter/fedora23`
* on all servers:
  * mkfs.xfs -i size=512 /dev/sdb
  * mkdir -p /data/brick1
  * echo '/dev/sdb /data/brick1 xfs defaults 1 2' >> /etc/fstab
  * mount -a && mount
  * yum install glusterfs-server
* on each server, permuting all combinations:
  * gluster peer probe `<ip>`
* on each server:
  *  mkdir /data/brick1/gv0
* on one server only:
  * gluster volume create gv0 replica 3 `<ip1>:/data/brick1/gv0` `<ip2>:/data/brick1/gv0` `<ip3>:/data/brick1/gv0`
  * gluster volume start gv0
* on one+ server:
  * mount -t glusterfs localhost:/gv0 /mnt

**Comment by erikh** [comment]
The fedora box really concerns me so I'm going to see if I can find an official yum repo to stuff in our ansible which will configure this.

The configuration on fedora is absolutely painless.

**Comment by yuva29** [comment]
1. Glusterfs supports various protocols for mounting (glusterfs, nfs, cifs, etc.) but currently I'm planning to focus on getting the {CRUD: glusterfs, Mount: glusterfs, Snapshot: glisters }
2. Also, it supports different types of volumes (distributed, replicated, striped, etc..) but I thought of getting the "distributed" (simplest one) working first.
3. Also, it provides various managing options (shrinking, expanding) and performance tuning options. I'm sure if we need to focus there right now?

I'm thinking to get the simplest possible option working(distributed volumes). let me know your thoughts.

**Comment by yuva29** [comment]
Here is the implementation [support glusterfs](https://github.com/contiv/volplugin/compare/master...yuva29:gluster?expand=1)
