### ISSUE TITLE
Volume CRUD queue

### ISSUE THREAD

**Issue by erikh** [contiv-experimental/volplugin#348]
#335 depends on this, I think at least. My initial testing suggested that volumes could be created as long as the brick exists but I think we still have to do this.

What we need is some kind of collection for volume creates. The collection should be parallel consumable and be able to be consumed on multiple hosts.

There are two use cases here:
- volume create takes longer than the HTTP timeout. We can adjust this value and even turn it off I think. However, it is much more resilient for the create to not be dependent on the HTTP connection.
- in glusterfs, replicas must be pre-created on multiple hosts; at least it seems that way right now.

I think an etcd watch is the right way to accomplish this. The watch can monitor a subtree of volume information (similar structure to `/volplugin/volumes` or `/volplugin/users/mount`). Setting a global for how many creates can run in parallel will also be required.

**Comment by mapuri** [comment]
@erikh very interesting problem. 

This has elements of asynchronous processing (addressable through a watch or kafka like pub-sub queue as you describe), however I am wondering if as a docker driver can these really be asynchronous? 

I remember very early on we had similar discussions especially in netplugin around having a configuration (desired) state and a runtime(operational) state. The goal there was that events are delivered as state creation and acted on by drivers (through a watch) in asynchronous way which later updates operational state to reflect the effects. 

However, one of the concerns about this model was that it becomes hard to give an immediate feedback (to docker). Do you see this being applicable here?

**Comment by erikh** [comment]
I think this would end up being a separate kind of service which volplugin signals to achieve its goal.

Yes, latency is an issue; but I think with the send-and-poll method we will be safe unless the queue is exceptionally large, and I don't believe it will be in any environment we will be deployed to. It does not take much time to format most volumes, xfs and ext4 (arguably the two serious filesystems on linux) are both quite fast.

Additionally, we could determine if the request is re-sent after a timeout and behave appropriately, which will happen if docker times out hitting the plugin due to its exponential backoff. While this operation is protected under lock right now, knowing it's already in the queue allows us to easily hijack the existing request into a new one due to the async nature of it all, aka you can just reattach to your create/remove process if it isn't finished yet. The behavior will need to be carefully tailored to ensure no mutable state is touched until the poll returns, though.

volplugin already does runtime parameters through its `watch` library and some probably too-clever use of pointers :)

**Comment by mapuri** [comment]
> I think with the send-and-poll method we will be safe unless the queue is exceptionally large

got it, so the docker API continues to block while backend processing will be asynchronous? Yeah, this shall work. From the use case `volume create takes longer than the HTTP timeout.`  I was somehow under the impression that docker itself was timing out due to volume create requests taking longer.

> I don't believe it will be in any environment we will be deployed to. It does not take much time to format most volumes, xfs and ext4 (arguably the two serious filesystems on linux) are both quite fast.

yep, I agree most common case won't have large queue build ups but those one off timeout cases are the tricky ones usually :) 

> volplugin already does runtime parameters through its watch library and some probably too-clever use of pointers :)

yes :) but iirc those watches have mostly be used for asynchronous stuff until now like snapshots where docker (plugin API) was not directly involved in blocking way.

**Comment by erikh** [comment]
> got it, so the docker API continues to block while backend processing will be asynchronous? 

Correct

> I was somehow under the impression that docker itself was timing out due to volume create requests taking longer.

Docker also has exponential backoff for retries, so we can inspect the state on retry to ensure that it as indeed created successfully, allowing the retry to safely work. This will be great for those larger volumes people need to provision regularly.

Cool. I think I'm going to start speccing this out in future comments. I have a good idea of how I want to do this now.

**Comment by mapuri** [comment]
sounds good, looking forward to the new infra !

**Comment by erikh** [comment]
Actually this may be simpler than a separate daemon, but good use of channels and a map might work.

**Comment by erikh** [comment]
(with the watches)
